fail-on-change = true

[formatter.java]
command = "google-java-format"
options = ["--replace"]
includes = ["*.java"]
excludes = []
priority = 0

[formatter.typescript]
command = "prettier"
options = ["--write"]
includes = ["*.ts", "*.js"]
excludes = []
priority = 0

[formatter.svelte]
command = "prettier"
options = ["--write"]
includes = ["*.svelte"]
excludes = []
priority = 0
