fail-on-change = true

[formatter.java]
command = "google-java-format"
options = ["--replace"]
includes = ["*.java"]

[formatter.typescript]
command = "prettier"
options = ["--write"]
includes = ["*.ts", "*.js"]

[formatter.svelte]
command = "prettier"
options = ["--write"]
includes = ["*.svelte"]

[formatter.openapi]
command = "prettier"
options = ["--write"]
includes = ["openapi.json"]
