spring.application.name=backend

# Thông tin k?t n?i Database
spring.datasource.url=jdbc:postgresql://localhost:5432/seal
spring.datasource.username=postgres
spring.datasource.password=1

# C?u hình Hibernate (T? ??ng log câu l?nh SQL ra console ?? d? debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto=update giúp Spring Boot t? ??ng t?o/s?a b?ng trong DB n?u b?n có vi?t code Model/Entity
spring.jpa.hibernate.ddl-auto=update